export const FETCH_TODO_LOADING='FETCH_TODO_LOADING';
export const FETCH_TODO_SUCCESS='FETCH_TODO_SUCCESS';
export const FETCH_TODO_FAILURE='FETCH_TODO_FAILURE';
export const ADD_TODO='ADD_TODO';
export const DELETE_TODO='DELETE_TODO';